spring:
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-03.cleardb.net/heroku_163966db0800ec5?reconnect=true
    username: bcd70bc5bcc283
    password: be507a35
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql